Version = 0
Id = "16459cd5-0456-11e7-9200-109add63ffcb"
Name = "cluffer"
PropertiesSchema = "schema_properties.json"
HashType = "sha2-256"

[Properties]
  description = "A Lisp Clutter/Twitter"
  language = "en"

[BasedOn]

[Zomes]
  [Zomes.Cluffer]
    Name = "Cluffer"
    Description = "Clutter in Lisp"
    Code = "zome_cluffer.zy"
    NucleusType = "zygo"
    [Zomes.Cluffer.CodeHash]
      H = [18, 32, 40, 228, 39, 245, 20, 91, 62, 66, 241, 205, 133, 201, 177, 0, 81, 4, 54, 64, 26, 158, 33, 53, 174, 54, 144, 151, 167, 228, 104, 70, 243, 189]
    [Zomes.Cluffer.Entries]
      [Zomes.Cluffer.Entries.handle]
        Name = "handle"
        DataFormat = "string"
        Schema = ""
        [Zomes.Cluffer.Entries.handle.SchemaHash]
      [Zomes.Cluffer.Entries.post]
        Name = "post"
        DataFormat = "string"
        Schema = ""
        [Zomes.Cluffer.Entries.post.SchemaHash]
      [Zomes.Cluffer.Entries.follow]
        Name = "follow"
        DataFormat = "string"
        Schema = ""
        [Zomes.Cluffer.Entries.follow.SchemaHash]
